"""empty message

Revision ID: 2185f821f5fa
Revises: b609cc111aa2
Create Date: 2023-05-09 22:27:26.998653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2185f821f5fa'
down_revision = 'b609cc111aa2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Tariff', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Tariff', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
