"""empty message

Revision ID: b609cc111aa2
Revises: 
Create Date: 2023-05-07 17:31:24.713095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b609cc111aa2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Dogovor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Manager',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fio', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Tariff',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('speed', sa.Integer(), nullable=False),
    sa.Column('tv', sa.Boolean(), nullable=True),
    sa.Column('video', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('User',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('number', sa.String(), nullable=True),
    sa.Column('balance', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clientid', sa.Integer(), nullable=False),
    sa.Column('tariffid', sa.Integer(), nullable=False),
    sa.Column('managerid', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('handled', sa.Boolean(), nullable=True),
    sa.Column('additional', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['clientid'], ['User.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['managerid'], ['Manager.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tariffid'], ['Tariff.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Request')
    op.drop_table('User')
    op.drop_table('Tariff')
    op.drop_table('Manager')
    op.drop_table('Dogovor')
    op.drop_table('Document')
    # ### end Alembic commands ###
